### ISSUE TITLE
InnerMost Component isn't firing 'WillMount', 'DidMount' when re-render

### ISSUE THREAD

**Issue by zhenkunou** [developit/preact#143]
in my case:

```
App:
  <div><Panel /></div>

Panel:
  <div><Title /></div>
   
render(<App/>, document.body)
```

when the `<Panel/>` re-render, the `<Title/>` isn't firing 'WillMount', 'DidMount' etc.

codepen: http://codepen.io/ryan_ou/pen/QNYegz?editors=0011

**Comment by developit** [comment]
@zhenkunou Looks like this is part of the regression in `4.6.1`, currently my top priority. I'll keep you posted as I progress.

**Comment by developit** [comment]
Fix is on the way! :)

**Comment by zhenkunou** [comment]
Awesome!

**Comment by developit** [comment]
@zhenkunou I've released this under the beta tag: `npm i -S preact@beta`

**Comment by developit** [comment]
Marking this as closed since both of our tests pass. I'll make an announcement when it's rolled out of beta :)

**Comment by developit** [comment]
Note: confirmed fix verification http://codepen.io/developit/pen/reXZvd?editors=0010

**Comment by zhenkunou** [comment]
Great work, Thanks!!!
Everything is fine, only one issue i found today, pls take a look. issue: #162

**Comment by zhenkunou** [comment]
@developit it seem that the bug is still here:

```
OuterComponent
  div
     Inner1Component
        div
          Inner2Component
            div
              Inner3Component
...

render(<OuterComponent />, document.body)
```
The `Inner3` Component 'DidMount' not being called when re-render.

codepen updated: http://codepen.io/ryan_ou/pen/QNYegz?editors=0011

**Comment by developit** [comment]
@zhenkunou Yikes! Sorry about that - I've got a fix coming.
